#wwwstat:	 wwwstat.c
#	@echo "Compiling wwwstat..."
#	@gcc -o wwwstat wwwstat.c


#wwwstat_full_1:	 wwwstat_full_1.c
#	@echo "Compiling wwwstat_full_1..."
#	@gcc -o wwwstat_full_1 wwwstat_full_1.c

wwwstat_full_2:	 wwwstat_full_2.c
	@echo "Compiling wwwstat_full_2..."
	@gcc -o wwwstat_full_2 wwwstat_full_2.c


